events {
    worker_connections 1024;
}

http {
    upstream product-service {
        server product-service:8000;
    }
    upstream order-service {
        server order-service:3000;
    }
    upstream user-service {
        server user-service:4000;
    }
    upstream notification-service {
        server notification-service:5000;
    }

    server {
        listen 80;

        location /products {
            proxy_pass http://product-service;
        }
        location /orders {
            proxy_pass http://order-service;
        }
        location /users/ {
            rewrite ^/users/(.*) /$1 break;
            proxy_pass http://user-service;
        }
        location /notify {
            proxy_pass http://notification-service;
        }
        location /health {
            return 200 '{"status":"gateway up"}';
            add_header Content-Type application/json;
        }
    }
}
